### ISSUE TITLE
Deployment AWS error 

### ISSUE THREAD

**Issue by SandyUgale** [Autodesk-Forge/bim360appstore-data.management-nodejs-transfer.storage#18]
I have followed every instruction you have given, it was working fine on Local but on AWS it was showing access denied error.. I checked permission as well..nothing is wrong ..

**Comment by augustogoncalves** [comment]
On AWS you need to specify the Lambda, the respective API Gateway and a payment plan. Do you have this last piece?

And what's the error message you're having? Maybe a print-scree or error description?
